import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  weight: ["400", "600", "700"],  
  style: ["normal", "italic"],   
  subsets: ["latin"],            
  variable: "--font-poppins",   
});

export const metadata: Metadata = {
  title: "Music Academy",
  description: "Generated by Talha Jamal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="shortcut icon" href="icon.svg" type="image/x-icon" />
      </head>
      <body
        className={`${poppins.variable}`}>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
